"""Assertion engine: evaluates the assertions stored in
tf.test_cases.expectations and persists one tf.assertion_results row each.

Assertion JSON (SQL kinds):
  {"name": ..., "kind": "sql_scalar", "sql": "...", "op": "eq", "expected": ...}
SQL may contain {placeholders} bound from the run context as query params
(prefix, file_id, file_id_0..N, as_of_0..N, target_worker, ...).

File kinds (evaluated in Python by the runner, which holds the fixture bytes):
  {"name": ..., "kind": "file_bytes", "file": "file_0", "op": "eq", "expected": true}
    - "file": "file_N" references the Nth fixture_sequence entry (0-based).
    - Verifies the bytes read back through the storage backend are
      byte-identical to what the runner generated (storage round-trip).
    - actual: True/False.
  {"name": ..., "kind": "file_rows", "file": "file_0", "op": "eq", "expected": 0}
    - Verifies every non-blank line of the generated file is accounted for:
      parseable lines (with a Worker_ID) must be in bronze.raw_worker_events
      (matched by row_hash = sha256 of the raw line, exactly as the loader
      computes it); unparseable / id-less lines must be in
      bronze.raw_worker_rejects (matched by line_no, 1-based over all lines
      including blanks, mirroring the loader).
    - actual: number of unaccounted lines (0 expected).
"""

from __future__ import annotations

import hashlib
import json
import operator
import re
from collections import Counter
from datetime import date, datetime
from decimal import Decimal
from typing import Any
from uuid import UUID

from pipeline import core as pipeline_core

OPS = {
    "eq": operator.eq, "ne": operator.ne,
    "gt": operator.gt, "gte": operator.ge,
    "lt": operator.lt, "lte": operator.le,
}

_TOKEN_RE = re.compile(r"\{(\w+)\}")


def substitute(sql_template: str, ctx: dict) -> tuple[str, dict]:
    tokens = _TOKEN_RE.findall(sql_template)
    missing = [t for t in tokens if t not in ctx]
    if missing:
        raise KeyError(f"assertion context missing placeholders: {missing}")
    params = {t: ctx[t] for t in tokens}
    # Escape every literal % (LIKE patterns, modulo) as %% first, so psycopg
    # never mistakes them for placeholders; then install %(name)s bindings.
    escaped = sql_template.replace("%", "%%")
    sql = _TOKEN_RE.sub(lambda m: f"%({m.group(1)})s", escaped)
    return sql, params


def _jsonable(value: Any) -> Any:
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, (bytes, bytearray)):
        return bytes(value).hex()
    return value


def _compare(op: str, actual: Any, expected: Any) -> bool:
    fn = OPS.get(op)
    if fn is None:
        raise RuntimeError(f"unknown comparator {op!r}")
    # be lenient about int/float/Decimal across the JSON<->SQL boundary
    if isinstance(actual, bool) or isinstance(expected, bool):
        return fn(bool(actual), bool(expected))
    if isinstance(actual, (int, float)) and isinstance(expected, (int, float)):
        return fn(actual, expected)
    return fn(actual, expected)


def _file_index(assertion: dict, ctx: dict) -> int:
    """Resolve assertion["file"] == "file_N" to the fixture part index."""
    ref = assertion.get("file", "")
    m = re.fullmatch(r"file_(\d+)", str(ref))
    if not m:
        raise RuntimeError(f"'file' must look like 'file_0', got {ref!r}")
    idx = int(m.group(1))
    if idx >= len(ctx.get("file_contents", [])):
        raise RuntimeError(
            f"'file' index {idx} out of range "
            f"({len(ctx.get('file_contents', []))} fixture files this execution)")
    return idx


def _eval_file_bytes(assertion: dict, ctx: dict) -> tuple[Any, str | None]:
    """Byte-identical storage round-trip: generated bytes vs bytes read back."""
    idx = _file_index(assertion, ctx)
    content = ctx["file_contents"][idx]
    uri = ctx["file_uris"][idx]
    backend = ctx["backend"]
    expected_sha = hashlib.sha256(content.encode("utf-8")).hexdigest()
    stored = backend.read_bytes(uri)
    actual_sha = hashlib.sha256(stored).hexdigest()
    ok = expected_sha == actual_sha
    msg = None if ok else (
        f"storage round-trip mismatch for {uri}: "
        f"generated sha256 {expected_sha[:16]}... != stored {actual_sha[:16]}...")
    return ok, msg


def _eval_file_rows(conn, assertion: dict, ctx: dict) -> tuple[Any, str | None]:
    """Every non-blank file line accounted for in bronze (events or rejects)."""
    idx = _file_index(assertion, ctx)
    content = ctx["file_contents"][idx]
    file_id = ctx.get(f"file_id_{idx}") or ctx.get("file_id")
    if not file_id:
        raise RuntimeError("no file_id in assertion context")

    good_hashes: Counter = Counter()   # sha256(raw line) -> count, parseable lines
    bad_lines: dict[int, str] = {}     # line_no -> raw, lines the loader rejects
    for lineno, raw in enumerate(content.splitlines(), start=1):
        if not raw.strip():
            continue  # loader ignores blank lines entirely
        obj, err = pipeline_core.parse_line(raw)
        if err is None and pipeline_core.extract_worker_id(obj) is None:
            err = "missing_worker_id"
        if err is None:
            good_hashes[pipeline_core.row_hash(raw)] += 1
        else:
            bad_lines[lineno] = raw

    with conn.cursor() as cur:
        cur.execute(
            "SELECT row_hash FROM bronze.raw_worker_events WHERE file_id = %s",
            (file_id,))
        bronze_hashes = Counter(r[0] for r in cur.fetchall())
        cur.execute(
            "SELECT line_no FROM bronze.raw_worker_rejects WHERE file_id = %s",
            (file_id,))
        reject_lines = {r[0] for r in cur.fetchall()}

    missing_good = list((good_hashes - bronze_hashes).elements())
    extra_bronze = list((bronze_hashes - good_hashes).elements())
    missing_bad = [ln for ln in bad_lines if ln not in reject_lines]
    unaccounted = len(missing_good) + len(extra_bronze) + len(missing_bad)
    msg = None if unaccounted == 0 else (
        f"{unaccounted} unaccounted lines for file_{idx}: "
        f"{len(missing_good)} parseable lines missing from bronze, "
        f"{len(extra_bronze)} unexpected bronze rows, "
        f"{len(missing_bad)} bad lines missing from rejects "
        f"(line_nos {sorted(missing_bad)[:10]})")
    return unaccounted, msg


def run_assertion(conn, assertion: dict, ctx: dict) -> dict:
    """Returns dict(status, expected, actual, message). Never raises."""
    name = assertion.get("name", "?")
    kind = assertion.get("kind", "sql_scalar")
    try:
        if kind in ("file_bytes", "file_rows"):
            if kind == "file_bytes":
                actual, msg = _eval_file_bytes(assertion, ctx)
            else:
                actual, msg = _eval_file_rows(conn, assertion, ctx)
            expected = assertion.get("expected")
            passed = _compare(assertion.get("op", "eq"), actual, expected)
            return {
                "name": name, "kind": kind,
                "status": "pass" if passed else "fail",
                "expected": expected, "actual": actual,
                "message": None if passed else (
                    msg or f"expected {expected!r} ({assertion.get('op')}), "
                           f"got {actual!r}"),
            }
        sql, params = substitute(assertion["sql"], ctx)
        with conn.cursor() as cur:
            cur.execute(sql, params)
            if kind == "sql_scalar":
                row = cur.fetchone()
                actual = _jsonable(row[0]) if row else None
            elif kind == "sql_row":
                row = cur.fetchone()
                actual = (
                    {k: _jsonable(v) for k, v in zip(
                        [d.name for d in cur.description], row)} if row else None
                )
            else:
                raise RuntimeError(f"unknown assertion kind {kind!r}")
        expected = assertion.get("expected")
        passed = _compare(assertion.get("op", "eq"), actual, expected)
        return {
            "name": name, "kind": kind,
            "status": "pass" if passed else "fail",
            "expected": expected, "actual": actual,
            "message": None if passed else (
                f"expected {expected!r} ({assertion.get('op')}), got {actual!r}"),
        }
    except Exception as exc:  # noqa: BLE001 - assertion failures must not kill the run
        return {
            "name": name, "kind": kind, "status": "error",
            "expected": assertion.get("expected"), "actual": None,
            "message": f"{type(exc).__name__}: {exc}",
        }


def persist_assertion(conn, *, run_id, test_case_id, execution_no, result: dict) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO tf.assertion_results
                (run_id, test_case_id, execution_no, name, kind, status,
                 expected, actual, message)
            VALUES (%s, %s, %s, %s, %s, %s, %s::jsonb, %s::jsonb, %s)
            """,
            (run_id, test_case_id, execution_no, result["name"],
             result["kind"], result["status"],
             json.dumps(result["expected"], default=str),
             json.dumps(result["actual"], default=str),
             result["message"]),
        )
